# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: local
        hooks:
        -   id: install-pre-commit-hooks
            name: Install latest version pre-commit hooks
            entry: pre-commit install
            language: system
            pass_filenames: false
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: local
        hooks:
        -   id: run-tests
            name: Run tests
            entry: python -m unittest discover -s test -p 'test_*.py'
            language: system
            pass_filenames: false